version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    ports:
    - 5433:5432 ## {port local (MYPC) : port docker}
  

## docker compose -p blogdb up -d